services:
  paperless-rest:
    build: ./paperless-rest
    ports:
      - "8080:8080"
    depends_on:
      - paperless-db

  paperless-ui:
    build: ./paperless-ngx-ui
    ports:
      - "80:80"

  paperless-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
      POSTGRES_DB: paperless
      
  paperless-queue:
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672

  paperless-ocr-worker:
    build: ./paperless-ocr-worker
    ports:
      - "8081:8081"
    depends_on:
      - paperless-queue

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ${HOME}/minio/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address :9090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/minio/login"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-s3-bucket:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 minio minio123 &&
      /usr/bin/mc mb minio/paperless"

#  elastic_search:
#    image: elasticsearch:8.7.1
#    environment:
#      - discovery.type=single-node
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "xpack.security.enabled=false"
#      - "xpack.security.enrollment.enabled=false"
#    # ulimits:
#    #   memlock:
#    #     soft: -1
#    #     hard: -1
#    ports:
#      - 9200:9200
#      - 9300:9300
#    kibanba:
#      image: docker.elastic.co/kibana/kibana:8.2.3
#      ports:
#        - 5601:5601
