services:
  paperless-rest:
    build: ./paperless-rest
    ports:
      - "8080:8080"
    depends_on:
      - paperless-db
  paperless-ui:
    build: ./paperless-ngx-ui
    ports:
      - "80:80"
  paperless-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
      POSTGRES_DB: paperless
  paperless-queue:
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
  paperless-ocr-worker:
    build: ./paperless-ocr-worker
    ports:
      - "8081:8081"
    depends_on:
      - paperless-queue
