services:
  paperless-rest:
    build: ./paperless-rest
    ports:
      - "8080:8080"
  paperless-ui:
    build: ./paperless-ngx-ui
    ports:
      - "80:80"
    depends_on:
      - paperless-rest
  paperless-db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
      POSTGRES_DB: paperless
